const LinupxActionTypes = {
    GET_LINEUPX_LOADING: "GET_LINEUPX_LOADING",
    GET_LINEUPX_FAQ_SUCCESS: "GET_LINEUPX_FAQ_SUCCESS",
    GET_LINEUPX_FAQ_FAIL: "GET_LINEUPX_FAQ_FAIL",
    GET_LINEUPX_CLIENTS_SUCCESS: "GET_LINEUPX_CLIENTS_SUCCESS",
    GET_LINEUPX_CLIENTS_FAIL: "GET_LINEUPX_CLIENTS_FAIL",
};

export default LinupxActionTypes;
